# Generated by Django 3.2.6 on 2021-12-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]


    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombreProducto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]