# Generated by Django 3.2.9 on 2021-12-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
        migrations.RenameModel(
            old_name='Local',
            new_name='tipoDeVentas',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='numero',
            new_name='numeroCliente',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='ciudad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='nombreProducto',
        ),
        migrations.RenameField(
            model_name='tipodeventas',
            old_name='camada',
            new_name='fechaVenta',
        ),
        migrations.RenameField(
            model_name='tipodeventas',
            old_name='nombre',
            new_name='productoVendido',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='esBueno',
        ),
    ]
